image: dist.hosts.rfi:5000/dind:kub

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
services:
- name: docker:dind
  command: ["--insecure-registry=dist.hosts.rfi:5000"]

before_script:
- docker info


stages:
  - build
  - build-admin
  - deploy-pre-production
  - deploy-pre-production-admin
  - deploy-production

build_job:
  stage: build
  script:
    - env
    - ansible-playbook ./ci.yml -t build -e "project_dir=$CI_PROJECT_DIR project=$CI_PROJECT_NAME tag=$CI_PIPELINE_ID project_folder=Identiy.STS.Identiy"

build_job:
  stage: build-admin
  script:
    - env
    - ansible-playbook ./ci.yml -t build -e "project_dir=$CI_PROJECT_DIR project=$CI_PROJECT_NAME tag=$CI_PIPELINE_ID project_folder=Identiy.Admin"

deploy_pre_production:
  stage: deploy-pre-production
  when: manual
  script:
    - ansible-playbook ./ci.yml -t deploy-pre-production -e "project_dir=$CI_PROJECT_DIR project=identity tag=$CI_PIPELINE_ID slug=$CI_PROJECT_PATH_SLUG project_folder=Identiy.STS.Identiy
  artifacts:
    paths:
      - preprod-identity.kub.yaml

deploy_pre_production_admin:
  stage: deploy-pre-production-admin
  when: manual
  script:
    - ansible-playbook ./ci.yml -t deploy-pre-production -e "project_dir=$CI_PROJECT_DIR project=identity-admin tag=$CI_PIPELINE_ID slug=$CI_PROJECT_PATH_SLUG project_folder=Identiy.Admin"
  artifacts:
    paths:
      - preprod-identity-admin.kub.yaml


deploy_production:
  stage: deploy-production
  when: manual
  script:
    - ansible-playbook ./ci.yml -t deploy-production -e "project_dir=$CI_PROJECT_DIR project=$CI_PROJECT_NAME tag=$CI_PIPELINE_ID slug=$CI_PROJECT_PATH_SLUG"
  artifacts:
    paths:
      - prod.kub.yaml
