version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identitystsidentity
    build:
      context: .
      dockerfile: src/Identity.STS.Identity/Dockerfile
      args:                                                                      
        BUILD_VERSION: 1.2.3.4    

  identity.admin:
    image: ${DOCKER_REGISTRY-}identityadmin
    build:
      context: .
      dockerfile: src/Identity.Admin/Dockerfile
      args:                                                                      
        BUILD_VERSION: 1.2.3.4
