version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
   
  identity.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IDENTITY_ADMIN_SEED=
      - AdminConfiguration__IdentityServerBaseUrl=http://10.0.75.1:5000

    ports:
      - "9000:80"
    
